### ISSUE TITLE
`xhost:  unable to open display ":0"`

### ISSUE THREAD

**Issue by ykla** [outpaddling/freebsd-update-notify#1]
FreeBSD 14.1 release amd64 KDE5 SDDM UEFI

```sh
ykla@ykla:~ $ /usr/local/libexec/freebsd-update-notify
2024年11月16日 星期六 17时06分04秒 CST
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
src component not installed, skipped
cd: /var/db/freebsd-update: Permission denied
Trying ykla...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
```
```sh
ykla@ykla:~ $ su
Password:
root@ykla:/home/ykla # /usr/local/libexec/freebsd-update-notify
2024年11月16日 星期六 17时06分19秒 CST
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
src component not installed, skipped
No updates are available to install.
Trying root...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
Trying sddm...
Failed.
Trying ykla...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
root@ykla:/home/ykla # 
```

It doesn't look like it can be run directly in the terminal, is there any other way to test this?

After install rxvt-unicode, And write `xhost +local:ykla` to `.profile`，then:

```sh
root@ykla:/home/ykla # /usr/local/libexec/freebsd-update-notify
2024年11月16日 星期六 17时15分25秒 CST
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
xhost:  unable to open display ""
src component not installed, skipped
No updates are available to install.
Trying root...
cat: /usr/local/etc/auto-admin/last-system-update: No such file or directory
````

Also cannot update pkg.

**Comment by outpaddling** [comment]
How did you set up your desktop environment?  freebsd-update-notify is normally a companion tool installed by sysutils/desktop-installer.  If you did not use desktop-installer, there is likely some missing configuration or package such as xauth.

It works for me under 14.2-BETA2 with KDE installed by desktop-installer:

![freebsd-14 2-KDE](https://github.com/user-attachments/assets/d845ad66-84e7-404e-bf25-afca338bb970)

**Comment by ykla** [comment]
> How did you set up your desktop environment? freebsd-update-notify is normally a companion tool installed by sysutils/desktop-installer. If you did not use desktop-installer, there is likely some missing configuration or package such as xauth.
> 
> It works for me under 14.2-BETA2 with KDE installed by desktop-installer:
> 
> ![freebsd-14 2-KDE](https://private-user-images.githubusercontent.com/11299711/386847257-d845ad66-84e7-404e-bf25-afca338bb970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjcxMDEsIm5iZiI6MTczMTgyNjgwMSwicGF0aCI6Ii8xMTI5OTcxMS8zODY4NDcyNTctZDg0NWFkNjYtODRlNy00MDRlLWJmMjUtYWZjYTMzOGJiOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Y2Y3N2FjZmM3ZTg3NzE2N2E5MjhiOTNlNmE3Y2IyOTFhMTRmZWJjMGJmYTBkOWM2ZDFlMGM3MDM3Nzk2NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WEQZCBGX_KZW73Q-be9TG9kE5qn4IwlUuMgExADku5Y)

`pkg install xorg sddm kde5 plasma5-sddm-kcm wqy-fonts xdg-user-dirs`

![)4(9WGFG{Z410POWRF{O3IP](https://github.com/user-attachments/assets/1b716577-6940-41b0-8ee4-92a6d5e78d5b)


But I also test desktop-installer in NEW installer.

This is the same result as before.

![~DG)~B7E4MCY6ZPXYPNO{2C](https://github.com/user-attachments/assets/a3ca2efe-9205-4800-825e-f49b65f4b7e7)

Are you logged into the desktop as root? I'm a regular user in the wheel group.


I am login as root:

![ded89514fc588d7bd216660076b23b6](https://github.com/user-attachments/assets/434f0f91-2450-41fb-84a0-e77197bbfa75)

It seems OK. But when you select `Yes`

![898816ac9649bf97737f070f4d7ed80](https://github.com/user-attachments/assets/630d1dc7-23b4-487c-83df-a14f90de2337)



```sh
root@ykla:~ # /usr/local/libexec/freebsd-update-notify
Sun Nov 17 16:16:54 CST 2024
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 7
Hours since last reminder = 24
Hours between reminders   = 24
No updates are available to install.
Trying root...
cat: /usr/local/etc/auto-admin/last-system-update: No such file or directory
root@ykla:~ # touch /usr/local/etc/auto-admin/last-system-update
root@ykla:~ # /usr/local/libexec/freebsd-update-notify
Sun Nov 17 16:18:53 CST 2024
Hours since last update   = 481064
Days since last update    = 20044
Max days between updates  = 7
Hours since last reminder = 24
Hours between reminders   = 24
No updates are available to install.
Trying root...
-su: /usr/local/bin/urxvt: not found
```

`pkg install rxvt-unicode`

![2016cff133fb3de3d60c8f491ab5992](https://github.com/user-attachments/assets/9bf928f4-a4bd-41c3-a6ce-9e98b47d1196)


Summary:

- Currently it doesn't work for normal users, it reports the error [xhost: unable to open display “:0”](https://github.com/outpaddling/freebsd-update-notify/issues/1#top)
- Missing file `/usr/local/etc/auto-admin/last-system-update` will result in an error that it doesn't exist unless you create it manually.
- Dependency packages are missing `x11/rxvt-unicode`.

**Comment by outpaddling** [comment]
OK, I see more clearly now.

1. freebsd-update-notify must be run by root, since it updates packages, ports tree, and base if the user selects 'yes'.  It is normally run as root by cron, not meant to be run manually.  That's why it's installed in libexec.
2. The missing last-system-update message is innocuous.  This file is created by auto-update-system after a successful update.  If it doesn't exist, freebsd-update-notify assumes it should check for updates.
3. The missing rxvt-unicode dep was overlooked because it's installed by qmediamanager via desktop-installer.  Thanks for the heads-up.  I will commit a fix shortly.
4. I don't recall offhand what needs to be done to enable X11 display access from an su session.  What's important, though, is that freebsd-update-notify works from cron.  You should see the update popup spontaneously when base updates are available, or the max update period has passed.  Edit /usr/local/etc/freebsd-update-notify/freebsd-update-notify.conf to change this.

**Comment by ykla** [comment]
In manually run tests without `last-system-update`, the program breaks immediately. 

But we need to test if it is running properly, we have to run the script manually. Or is there another way to quickly reproduce the results？Set 

```ini
max-days-between-updates    0          
hours-between-reminders     0
```

?


And for my test, you must login via root for sddm,  then you can run your script without error `unable to open display ":0"`. Same with you just login with root in tty and run `startx`.

But if you login sddm via normal wheel user, even you `su`, you will also get error `unable to open display ":0"`.

**Comment by ykla** [comment]
I login KDE5 via sddm by user `ykla`:

```sh
ykla@ykla:~ $ id
uid=1001(ykla) gid=1001(ykla) groups=1001(ykla),0(wheel)
```


I set ` /usr/local/etc/freebsd-update-notify/freebsd-update-notify.conf ` as :

```ini
max-days-between-updates    0          
hours-between-reminders     0
```

I waited a while and watched the system log.

see slao `/var/log/freebsd-update-notify`:

```sh
root@ykla:/home/ykla # cat /var/log/freebsd-update-notify
Sun Nov 17 22:00:00 CST 2024
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
src component not installed, skipped
No updates are available to install.
Trying root...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
Trying sddm...
Failed.
Trying ykla...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
```

` /var/log/freebsd-update-cron`: 

```sh
root@ykla:/home/ykla # cat /var/log/freebsd-update-cron
       0 freebsd-update cron process(es) detected.
src component not installed, skipped
There are updates available to install.
Run 'freebsd-update [options] install' to proceed.
```


No any notify in my desktop.

**Comment by outpaddling** [comment]
Manually running under an su session works for me on 14.1-RELEASE with Lumina and xdm, and under 14.2-BETA2 with KDE and sddm.
I would suggest trying to run a simple X11 client like urxvt from your su session.  This works on my installations.  If that works, then I think freebsd-update-notify should work as well.  If not, look into enabling X11 display access from su sessions.  As I recall, there is some configuration that needs to be done, but I don't remember what it is at the moment.  I created desktop-installer to relieve people from this sort of drudgery.  The answer is in desktop-installer or one of the auto-admin scripts it uses.

**Comment by ykla** [comment]
> Manually running under an su session works for me on 14.1-RELEASE with Lumina and xdm, and under 14.2-BETA2 with KDE and sddm. I would suggest trying to run a simple X11 client like urxvt from your su session.

Please see 

![image](https://github.com/user-attachments/assets/6481574f-28ae-4a49-a046-ab45dfea1527)

And I test via root login sddm, It will show me notify :

![1984c1ca5a1107f1ec3c2b929807ba9](https://github.com/user-attachments/assets/dc68963f-d4e5-4199-b102-6aaa43e3a667)

But when I select the `Yes`, It breaks.

See also 

```sh
root@ykla:/home/ykla # cat /var/log/freebsd-update-notify
Sun Nov 17 23:00:00 CST 2024
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
src component not installed, skipped
No updates are available to install.
Trying root...
cat: /usr/local/etc/auto-admin/last-system-update: No such file or directory
```

**Comment by ykla** [comment]
In short, your script doesn't work for desktops where regular users are logged in. It will report `error: unable to open display “:0”`, either by running `/usr/local/libexec/freebsd-update-notify` in the terminal using `su` or by waiting for it to run automatically in the background.

Your script will only work if root is logged into the desktop. And there is still the error `/usr/local/etc/auto-admin/last-system-update` does not exist. The program will not work unless you manually `touch` the issue. After you click `yes`, the program exits without any errors, and a look at the log will show that the above file does not exist.




--- 

How can I install kde5? Just: 

```sh
# pkg install xorg sddm kde5 plasma5-sddm-kcm wqy-fonts xdg-user-dirs
# sysrc dbus_enable="YES"
# sysrc sddm_enable="YES"
# echo "exec ck-launch-session startplasma-x11" > ~/.xinitrc
```

Above, with or without `desktop-installer`, I've tested via `desktop-installer` install kde5 and the results are consistent.

**Comment by outpaddling** [comment]
OK, I kept playing with this since my last response, and oddly enough it failed on my KDE + sddm installation, where it previously worked and no changes have been made.  There must be a bug in some underlying system causing intermittent problems.

I did find that freebsd-update-notify authorizes itself using xhost.  Changing 'su -l' to 'su -m' there fixed the authorization issue.  Try making this change to /usr/local/libexec/freebsd-update-notify (only for the xhost command, not the rest) and let me know what happens.

**Comment by ykla** [comment]
```sh
ykla@ykla:~ $ su -m
Password:
root@ykla:~ #  /usr/local/libexec/freebsd-update-notify 
2024年11月17日 星期日 23时18分40秒 CST
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
src component not installed, skipped
No updates are available to install.
Trying root...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
Trying sddm...
Failed.
Trying ykla...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
```

**Comment by outpaddling** [comment]
And change:
```
previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update)
```
to
```
previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update || `true)`
```
I was mistaken about the warning being innocuous.

**Comment by outpaddling** [comment]
> ```shell
> ykla@ykla:~ $ su -m
> Password:
> root@ykla:~ #  /usr/local/libexec/freebsd-update-notify 
> 2024年11月17日 星期日 23时18分40秒 CST
> Hours since last update   = unknown
> Days since last update    = 7
> Max days between updates  = 0
> Hours since last reminder = 24
> Hours between reminders   = 0
> Authorization required, but no authorization protocol specified
> 
> xhost:  unable to open display ":0"
> Authorization required, but no authorization protocol specified
> 
> xhost:  unable to open display ":0"
> src component not installed, skipped
> No updates are available to install.
> Trying root...
> Authorization required, but no authorization protocol specified
> 
> xwininfo: error: unable to open display ":0"
> Failed.
> Trying sddm...
> Failed.
> Trying ykla...
> Authorization required, but no authorization protocol specified
> 
> xwininfo: error: unable to open display ":0"
> Failed.
> ```

No, I mean change 
```
su -l $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true
```
to
```
su -m $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true
```
in the freebsd-update-notify script.

**Comment by ykla** [comment]
```
root@ykla:/home/ykla # /usr/local/libexec/freebsd-update-notify
2024年11月17日 星期日 23时23分28秒 CST
Hours since last update   = unknown
Days since last update    = 7
Max days between updates  = 0
Hours since last reminder = 24
Hours between reminders   = 0
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
Authorization required, but no authorization protocol specified

xhost:  unable to open display ":0"
src component not installed, skipped
No updates are available to install.
Trying root...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
Trying sddm...
Failed.
Trying ykla...
Authorization required, but no authorization protocol specified

xwininfo: error: unable to open display ":0"
Failed.
root@ykla:/home/ykla # 
```

**Comment by ykla** [comment]
```sh
#!/bin/sh -e

record_reminder_time()
{
    current_time=$(date '+%s')
    current_time=$((current_time / 3600))
    mkdir -p $CONF_DIR
    printf "$current_time\n" > $CONF_DIR/last-reminder
}

hours_since_reminder()
{
    current_time=$(date '+%s')
    current_time=$((current_time / 3600))
    reminder_file=$CONF_DIR/last-reminder
    if [ -e $reminder_file ]; then
	last_reminder=$(cat $reminder_file)
	printf "$((current_time - last_reminder))\n"
    else
	# Assume updates are needed
	printf "24\n"
    fi
}

# Run as root by cron. Protect against trojans.
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

CONF_DIR=/usr/local/etc/freebsd-update-notify

# Place a time stamp in the log
date

# pgrep doesn't find freebsd-update-notify processes.
# Read the man page thoroughly and tried all relevant flags
# This oddly causes two freebsd-update-notify processes to be spawned
# running=$(ps ax | fgrep -v fgrep | fgrep freebsd-update-notify | wc -l)
# Use a temp file instead
tmpfile=$(mktemp)
ps ax | fgrep -v fgrep | fgrep libexec/freebsd-update-notify > $tmpfile || true
running=$(cat $tmpfile | wc -l) # Use a pipe to hide filename from wc
rm -f $tmpfile
if [ $running -gt 1 ]; then
    printf 'freebsd-update-notify is already running.\n'
    exit 0
fi

# Notifications are only generally useful on the console
DISPLAY=:0
export DISPLAY

CONF_FILE=$CONF_DIR/freebsd-update-notify.conf

hours_since_update=$(/usr/local/sbin/auto-last-update)
if [ $hours_since_update = unknown ]; then
    # Assume updates are needed
    days_since_update=7
else
    days_since_update=$(( $hours_since_update / 24 ))
fi

# Max time between updates if no freebsd-update activity
# This ensures that packages are kept up-to-date when months pass
# between base updates
max_days_between_updates=$(awk '$1 == "max-days-between-updates" { print $2 }' $CONF_FILE)

# Make sure this matches cron file
hours_between_reminders=$(awk '$1 == "hours-between-reminders" { print $2 }' $CONF_FILE)

printf "Hours since last update   = $hours_since_update\n"
printf "Days since last update    = $days_since_update\n"
printf "Max days between updates  = $max_days_between_updates\n"
printf "Hours since last reminder = $(hours_since_reminder)\n"
printf "Hours between reminders   = $hours_between_reminders\n"

# Find out who owns DISPLAY
display_users=$(ps -aexwwj | grep "DISPLAY=$DISPLAY_ID" | awk '{ print $1 }' | sort -u)

# Make sure root can access the local display
# NetBSD laptop, quagga
for user in $display_users; do
    su -m$user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true
done

if freebsd-update updatesready || \
    [ $days_since_update -ge $max_days_between_updates ]; then
    if [ $(hours_since_reminder) -ge $hours_between_reminders ]; then
	for user in $display_users; do
	    # Zenity --question returns 0 if the user clicks Yes, but
	    # the exit code of su is not the exit code of zenity.
	    # Create a file if zenity returns 0 so we can determine the
	    # yes/no response after.
	    # su returns 0 if it can access the DISPLAY.
    
	    printf "Trying $user...\n"
	    # Test access to the DISPLAY
	    if su -m $user -c "env DISPLAY=:0 xwininfo -root" > /dev/null; then
		# If we can access the display, start dialog
		if su -m $user -c "/usr/local/bin/zenity --display=:0 --question --text='Updates are available.\nInstall and reboot now?'" > /dev/null; then
		    previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update || `true`)
		    su -m $user -c '/usr/local/bin/urxvt -e auto-update-system --pause --yes > /dev/null'
		    new_update_time=$(cat /usr/local/etc/auto-admin/last-system-update)
		else
		    su -m $user -c "/usr/local/bin/zenity --display=:0 --info --text='You will be reminded again in $hours_between_reminders hours.\nYou can update manually any time by running\n\n\tauto-admin'" > /dev/null
		    record_reminder_time
		fi
		break   # Don't repeat for other users in $display_users
	    else
		printf "Failed.\n"
	    fi
	done
    fi
fi
```
It works. I changed all `su -l` to `su -m`, and

write 

```
previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update || `true`)
```

![6~W@3`4K@KI39HDDOK`OXCO](https://github.com/user-attachments/assets/7b132453-9d49-4efd-b556-351a55cbb5ff)

**Comment by outpaddling** [comment]
OK, I'll push these changes ASAP.  Thanks for the detailed feedback!  Feel free to reopen if any problems reoccur.

**Comment by ykla** [comment]
If I just changed `su -m $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true` it will also get error. So I changed all  `su -l` to `su -m`

**Comment by outpaddling** [comment]
> In short, your script doesn't work for desktops where regular users are logged in. It will report `error: unable to open display “:0”`, either by running `/usr/local/libexec/freebsd-update-notify` in the terminal using `su` or by waiting for it to run automatically in the background.
> 
> Your script will only work if root is logged into the desktop. And there is still the error `/usr/local/etc/auto-admin/last-system-update` does not exist. The program will not work unless you manually `touch` the issue. After you click `yes`, the program exits without any errors, and a look at the log will show that the above file does not exist.

This is not true.  It is well-tested with regular users logged in, but you have uncovered two issues where it fails:

1. xhost failing to authorize access to the display in some situations
2. Failure when auto-update-system has never been run before

> 
> How can I install kde5? Just:
> 
> ```shell
> # pkg install xorg sddm kde5 plasma5-sddm-kcm wqy-fonts xdg-user-dirs
> # sysrc dbus_enable="YES"
> # sysrc sddm_enable="YES"
> # echo "exec ck-launch-session startplasma-x11" > ~/.xinitrc
> ```
> 
> Above, with or without `desktop-installer`, I've tested via `desktop-installer` install kde5 and the results are consistent.

I can't support manually installing and configuring desktop environments like KDE.  There are far too many variables and it would take countless hours of conversation to identify problems.  This is why I created desktop-installer to embody the knowledge required.  If you want to explore this, I'd suggest opening a discussion on the appropriate forums or mailing lists.  Do a search first, as this has likely been discussed many times before.

**Comment by outpaddling** [comment]
> If I just changed `su -m $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true` it will also get error. So I changed all `su -l` to `su -m`

I can't reproduce this.  Once the display is authorized by xhost, either su -l or su -m works for me for the rest of the session, as I would expect.

Where is it failing exactly?  The only potential issue I can see is maybe DISPLAY is not set for the urxvt command.  Try reverting everything but the xhost command to 'su -l' and add 'env DISPLAY=:0' to the urxvt command:

```
su -l $user -c 'env DISPLAY=:0 /usr/local/bin/urxvt -e auto-
update-system --pause --yes > /dev/null'
```

**Comment by outpaddling** [comment]
I've reverted the 'su -m' to just 'su', which seems to preserve enough of the env for xhost to function, but does not inherit aliases from the calling user.

I also added xhost and xwininfo as port dependencies, so it should function completely independently from desktop-installer now (assuming the system is properly configured by other means).
